[build]
  publish = "build/web"
  command = "flutter pub get && flutter build web --release"

[build.environment]
  FLUTTER_VERSION = "3.19.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true 